### PR TITLE
Added 'hours' & 'date' as optional flags to export

### LINKED ISSUE #32: [FEATURE] Adding an optional 'date' & 'hours' field to the 'zeit export' command.
Hey, just something I've been implementing in my personal varation of this as I find it quite usefull is to have two additional fields in the 'export' JSON that comes out of `zeit export` . 

- Date (showing 'DD-MM-YYYY') 
- Hours (Hours,  with decimal precision, that this task has been tracked) 

Now I think since maybe not everyone wants these it would be best to make them 'optional' so that you have to enable them. 

Some questions for that, that I would have then would be. 
 
 - What should the 'shortcuts' for the flags be? (-h and -d)  ? 

Let me know if this is something that might be interesting, and I can make a PR for it in time. 
And also, any additional requierements or things it should do.

Best

### PR DESCRIPTION
**Pull request by MaximilianSoerenPollak**
Added both hours and date to both export types.
Choose the 'string' datatype as that makes it easiest to fit in the way the project is structured. 
```sh
date -> 'DD-MM-YY' -> '03-04-2020' 
hours -> 3.45  # uses the 'fmtHours' function 
```
Both flags are optional and by default disabled.

Build successfully with 'make VERSION=0.0.8' and tested both outputs with the optional flags. -> Output as desired.

Let me know if any other changes are requiered or wanted, and I adapt as needed. 

This should close #32

### CODE REVIEW

**Review by mrusme — CHANGES_REQUESTED** [review]
First of, thanks for the PR!

As you might have noticed, I didn't really care for a programming language dictating me what indentation to use. Hence there's a `.editorconfig` in the repo root. Could you make your editor honor it and force push a reformatted version of your PR? It's really hard to go through, and I wouldn't want incremental changes in indentation across the code.

One point that I'm already seeing is the extension of `Entry`. I think discarding the data using `json:"-"` would be better, as we wouldn't want that information to somehow end up in the database.

Also, I saw that you added two range loops, one for each flag. I think it makes sense to consolidate them, just to save some time/computing power for very large exports. Wdyt?

**Comment by MaximilianSoerenPollak** [comment]
I see, I mean in Go you have the benefit that it only has one offical formatter that can´t be configured so if you formatt it with it it's always the same, not like JS where you have 2000+ and each can confiigured differently. 

But I will integrate the .editorconfig to format it correctly as suggested, to make the PR more readable & conform to the project.

Can you elaborate on which fields exactly to disregard? Cause anything we do '-' on, also won´t be exported in the end then as far as I tested it. 


Imo Go won´t suffer much time/performance loss in forloops unlike Python but I still can put it into one loop to make it nicer / more concise

**Comment by MaximilianSoerenPollak** [comment]
It's very difficult to enforce 'Go' to use spaces instead of tabs, as that's what the default formatter does. 
So might be a consideration to change that in future projects if wanted.

**Comment by MaximilianSoerenPollak** [comment]
I will open a new PR, as this one I can´t rescue with the formatting.

**Comment by MaximilianSoerenPollak** [comment]
Additional posting this comment as well on this PR: 


Nope.. it does not let me push the code without it completly formatting. I'm sorry. I can't then do a PR. 

My apologies. 

If you still want to see the changes and commit them yourself you can view the PR by 'ignorign Whitespace' in the GIthub viewer. 
Or just copy the code underneath. 

-> Define hours & date argument variables 
`rootCmd.go`
```go
//...
var exportHours bool 
var exportDate bool 
//...
```

 -> Add Date & Hours to the entry struct 
-> Add 'SetDateFromBegin' function 

`entry.go` 
```go
type Entry struct {
//...
Date string `json:"date,omitempty"`
Hours string`json:"hours,omitempty"`
//...
}

func (entry *Entry) SetDateFromBegin() {
entry.Date = entry.Begin.Format("02-03-2006") // DD-MM-YYYY
} 
```
-> Add hours & dates to the arguments 
-> Add addtional information to the output if wanted

`exportCmd.go`
```
//...
if exportHours || exportDate {
	var addedInformationEntries []Entry
	for _, v := range filteredEntries {
		if exportHours {
			v.Hours = fmtHours(v.GetDuration())
		}
		if exportDate {
			v.SetDateFromBegining()
		}
		addedInformationEntries = append(addedInformationEntries, v)
	}
	// Reasignment here so we don't need to check other flags later
	filteredEntries = addedInformationEntries
}
//...
exportCmd.Flags().BoolVar(&exportDate, "date", false, "Add the 'date' field to the export")
exportCmd.Flags().BoolVar(&exportHours, "hours-decimal", false, "Add an 'hours' field calculated with '--decimal' to the export")
//...
```
And lastly in `tyme.go` add the 'Hours & Date` to the struct & the intialisation. 


I hope this helps at bit at least.

**Pull request closed without merging**
