### PR TITLE
cleanUp: use tx.Get for getting values from DB

### PR DESCRIPTION
**Pull request by miltkall**
tx.AscendKeys can be used for collecting multiple keys, values.
In our case we only collect one key, value therefore use tx.Get

Concerning [this](https://github.com/mrusme/zeit/issues/20) issue. Enjoy 😄

### CODE REVIEW

**Comment by miltkall** [comment]
Just came into my mind. Do you use any special formater for golang?

**Comment by mrusme** [comment]
Check [this](https://github.com/mrusme/zeit/blob/master/.editorconfig). But I know that Go tooling will force their style upon anyone, so it's hard to use both in general.

Will test the PR asap!

**Comment by mrusme** [comment]
Tested, works, thank you! Could you `:%s/\t/  /gI` on the `z/database.go` in order to replace tabs with spaces? Thought of quickly doing it but didn't want to rain on your parade by overriding your changed lines, heh.

**Review by mrusme — CHANGES_REQUESTED** [review]
\t -> space space

**Comment by miltkall** [comment]
Sorry for the delay. I was travelling. No stable internet 😅 .

Many thanks for the .editorconfig. Do you use it in combination with nvim? Want to move from VSCode to NVIM, but I was overwhelmed from your nvim config 😅. Your dotfiles are god level 👏🏿.

I made the requested change and thanks for your kind words. You website/blog is amazing! You have redefined, how an interesting person, tech guru, photographer, traveler ... should be 💯

**Review by mrusme — APPROVED** [review]

**Comment by mrusme** [comment]
> Do you use it in combination with nvim? Want to move from VSCode to NVIM, but I was overwhelmed from your nvim config 😅. Your dotfiles are god level 👏🏿.

Thank you good sir! Yes, indeed, I'm using NeoVim and I have the editorconfig plug, so that nvim will automatically adjust indentation, max line length, etc. :-) You probably saw it [here](https://github.com/mrusme/dotfiles/blob/96a18c1acfff65353dc17c206bc6ca2f3e1543b0/nvim/init.vim#L26) and [here](https://github.com/mrusme/dotfiles/blob/96a18c1acfff65353dc17c206bc6ca2f3e1543b0/nvim/init.vim#L491). As for an easy start you can check out [SpaceVim](https://spacevim.org), [Doom Nvim](https://github.com/NTBBloodbath/doom-nvim), as well as [other dotfiles](http://dotfiles.github.io/)!

Thank you for the PR. 👍🏼

**Pull request merged**
